/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package watersanitationgame.Ending_Jesse;

import javax.swing.ImageIcon;
import watersanitationgame.Save;

/**
 *
 * @author jesse
 */
public class EndingGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EndingGUI.class.getName());
        String endingText;
        Ending ending;
        EndingCalculation endingCalculation;
        int saveIndex;
        
        
        
    

    /**
     * Creates new form endingGUI
     */
    public EndingGUI(int saveNum) {
        
        initComponents();
        
        saveIndex = saveNum;
        endingCalculation = EndingCalculation.getInstance();
        
        endingCalculation.readData(saveIndex);
        endingCalculation.save();
        ending = endingCalculation.createEnding();
        
        endingText = ending.displayEnding();
        
        endingTA.setText(endingText+ "\n\n\nClick the next button to see what effect your choices had or select the \nVIEW PAST RESULTS to view previous saves");
        
        ImageIcon image = new ImageIcon(getClass().getResource(ending.getImage()));
        
        imageLBL.setIcon(image);
        
        scoreLBL.setText("Score: "+endingCalculation.getSave().getGameScore() + "/100");
        
        
        
    }

    private EndingGUI() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        endingTA = new javax.swing.JTextArea();
        nextBTN = new javax.swing.JButton();
        imageLBL = new javax.swing.JLabel();
        scoreLBL = new javax.swing.JLabel();
        pastresultsBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        endingTA.setEditable(false);
        endingTA.setColumns(20);
        endingTA.setRows(5);
        endingTA.setText("The ending text will display here.\n\n");
        endingTA.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(endingTA);

        nextBTN.setBackground(new java.awt.Color(204, 204, 204));
        nextBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nextBTN.setText("NEXT");
        nextBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nextBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBTNActionPerformed(evt);
            }
        });

        scoreLBL.setText("Score: ");

        pastresultsBTN.setBackground(new java.awt.Color(204, 204, 204));
        pastresultsBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pastresultsBTN.setText("DISPLAY PAST RESULTS");
        pastresultsBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pastresultsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastresultsBTNActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(pastresultsBTN)
                        .addGap(181, 181, 181)
                        .addComponent(nextBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(scoreLBL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(imageLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(scoreLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextBTN)
                    .addComponent(pastresultsBTN))
                .addGap(36, 36, 36))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBTNActionPerformed
        ResultsGUI resultsGUI = new ResultsGUI(endingCalculation.getSave(), false);
        resultsGUI.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_nextBTNActionPerformed

    private void pastresultsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastresultsBTNActionPerformed
        PastResultsGUI pResultsGUI = new PastResultsGUI(saveIndex);
        pResultsGUI.setVisible(true);
    }//GEN-LAST:event_pastresultsBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EndingGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea endingTA;
    private javax.swing.JLabel imageLBL;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextBTN;
    private javax.swing.JButton pastresultsBTN;
    private javax.swing.JLabel scoreLBL;
    // End of variables declaration//GEN-END:variables
}
